name: Benchmark

on:
  workflow_dispatch:

jobs:

  benchmark:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
            python-version: "3.12"
        name: 'Setup python'
      - shell: bash
        run: |
          pip install pytest-benchmark[histogram]
        name: 'Install pytest-benchmark'
      - shell: bash
        run: |
          pip install tslearn[all_features]~=0.7.0 && pytest --benchmark-save=0.7
        name: 'Benchmark v0.7'
      - shell: bash
        run: |
          pip install tslearn[all_features]~=0.8.0 && pytest --benchmark-save=0.8
        name: 'Benchmark v0.8'
      - shell: bash
        run: |
          pip install 'tslearn[all_features] @ https://github.com/tslearn-team/tslearn/archive/main.zip' && pytest --benchmark-save=latest
        name: 'Benchmark latest'
      - shell: bash
        run: |
          pytest-benchmark compare --group-by func --histogram benchmark
        name: 'Compare benchmark'
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          path: benchmark*.svg
